### PR TITLE
Correction to the grunt task `build` to provide the env var

### PR DESCRIPTION
**Pull request by jeremyBass**
This correction seems to fix issue raised in [PR] #327 following
https://github.com/washingtonstateuniversity/WSU-spine/pull/327#issuecomment-169796527
.  Local build seemed to be correct

### CODE REVIEW

**Comment by jeremyfelt** [comment]
Does the `env:prod` not carry over from `grunt prod`? https://github.com/washingtonstateuniversity/WSU-spine/blob/develop/Gruntfile.js#L39-L45

**Comment by jeremyBass** [comment]
Aw you are running `grunt prod` on the server, was thinking it was just `grunt build` and tested that area. I don't know a 100% if it is having the issue where it is not carrying over, I'll have to test that.  It is possible that a nested task may be losing scope.  Could be that the issue maybe rooted somewhere else.  I'll try to test later today.

**Comment by jeremyBass** [comment]
ok, I thought it was due to something with the node package, but it looks like there has been things removed all over and holes created in the test stuff root from there .. https://github.com/washingtonstateuniversity/WSU-spine/commit/90b03a0937d34c0332367923729def16a14d8ba8#diff-540d13424b85f86747c3137b36f419d4L5

I'm not sure of the full loss of function across the test area, but I did notice that there are parts that were needed and have been removed.  Include and replace seems like another one with the preprocessor.  I would have to dig to know more.

**Comment by jeremyfelt** [comment]
Ahh yeah, that was all ripped out in favor of the working test solution. I wouldn't spend much time fixing the development environment stuff. I'm not sure that we have an existing related bug.

**Comment by jeremyBass** [comment]
I just did a build, it doesn't seem that all of the build of the visual end of the tests is correct anymore.  The test to see if the grid layouts between `fixed`, `hybrid`, and `fluid` all say `hybrid` (http://repo.wsu.edu/spine/1/tests/grid_fluid.html for example).  That is just a quickie look.  I didn't run through to find out where anything else is not preforming.

**Comment by jeremyfelt** [comment]
Right, that's one of the bugs I found and fixed in a previous iteration. I'm not sure how long that's been broken. The current `develop` branch has those changes - http://repo.wsu.edu/spine/develop/tests/grid_fluid.html

I'm focused pretty heavily on this at the moment, so there may be additional test HTML changes coming.

**Comment by jeremyfelt** [comment]
ec103d96d0d4806088c64933064e084bc6afb80d is the specific commit that resolved the `hybrid` bug.

**Comment by jeremyBass** [comment]
aw got ya

**Pull request closed without merging**
