### PR TITLE
[IN PROGRESS] Make default theme provided by WSU Spine WCAG 2.0 AA compliant

### PR DESCRIPTION
**Pull request by jeremyfelt**
## Purpose

As part of WSU's agreement with the OCR, the default template offered by the University must be WCAG 2.0 AA compliant within the next 30 days.

This will be a breaking change to the WSU Spine in that we will not be able to force its implementation on existing sites blindly. We will ship a Spine 2.0.0 and adjust sites on a case by case basis. Sites built from that point forward will need to use the latest version to help ensure they are meeting WCAG 2.0 AA guidelines.

## General Work
* Adds a handful of style guide files
* Build out more typography to test in style guide file

## Accessibility
* Add markup and styles for screen reader shortcuts to navigation and main.
* Remove `vellum`, the transparent Spine, to avoid contrast issues.
* Darken default body text color to `#2a3033`.
* Set body text to the root size (usually 16px).
* Improve input styles—color (`#717171`) and font size (16px).
* Restore default browser `outline` behavior on focus.
* Restore default browser underlines on anchors to provide a non-color indicator of links in body text.
* Restore `:focus` outline on Spine action tab buttons.
* Avoid trapping keyboard users in the Spine search input field.
* Improve search input usability, styles.
* Match some focus styles to hover styles for anchors in Spine and body text.

### CODE REVIEW

**Comment by jeremyBass** [comment]
What will be the breaking changes?  That was not fully clear here.

**Comment by jeremyfelt** [comment]
@jeremyBass I think we still need to clearly identify them, but they are all visual rather than functional. One that immediately stands out is the removal of `text-decoration: none` on anchors by default. We don't want to push that out as a forced visual change due to how it's already been approached on other sites.

**Comment by jeremyBass** [comment]
@jeremyfelt I follow, thank you for the heads up.  I will keep an eye out for the list.

**Comment by jeremyfelt** [comment]
I'm going to merge this into the develop branch for additional testing over the next 2 weeks. A `1.x-develop` branch has been created for additional 1.x bug fixes. Our target release date for 2.0.0 is February 26.

**Pull request merged**
