### PR TITLE
[PR] Apply a common style/spacing across all SCSS files

### PR DESCRIPTION
**Pull request by jeremyfelt**
Mostly implements the [jQuery CSS style guide](https://contribute.jquery.org/style-guide/css/) as part of a deep dive through all files looking for issues. The before/after of generated CSS does not change, except for a couple inline comments.

We should normally avoid changing code style just to change it, as it makes searching through the history of a file harder. However, the history of our CSS files is not well documented in most commits up until this point. Cleaning now allows us to reset the files a bit so that a clear path exists when making future changes.

Future changes should be well documented in issues and in commits.

:smile: :sparkles: :stars:

### CODE REVIEW

**Comment by jeremyfelt** [comment]
Merging to the `develop` branch, which will be merged into a new Spine version at the beginning of January.

**Comment by natejacobson** [comment]
Such a flurry. Looking forward to seeing the big unveil in January.

**Comment by jeremyfelt** [comment]
A large flurry for mostly unnoticeable improvements that sets the stage for a smaller flurry for slightly more noticeable improvements. :)

**Comment by natejacobson** [comment]
Sometimes the thankless, behind-the-scenes work is the most important. Plus, I may be one of the few who WILL notice :)

**Pull request merged**
